restylers:
  - dotnet-format:
      command:
        - "dotnet"
        - "format"
        - ".\\ViSort\\ViSort.sln"
  - "shellcheck"
  - "shfmt"
  - "jq"
  - "taplo"
  - "prettier-markdown"
  - "prettier-yaml"
