name: Create Tag

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  create-tag:
    name: Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get version
        uses: sergeysova/jq-action@v2
        id: version
        with:
          cmd: jq -r .version ViSort/appsettings.json

      - uses: fregante/setup-git-user@v2

      - name: Create tag
        run: scripts/create_tag.sh "${{ steps.version.outputs.value }}"
