name: Dotnet Check

on:
  push:
    paths:
      - "**/*.cs"
      - "**/.editorconfig"
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run dotnet format
        uses: xt0rted/dotnet-format@v1
