name: Dotnet Check

on:
  push:
    paths:
      - "**/*.cs"
      - "**/.editorconfig"
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  check-format:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Run dotnet format check
        working-directory: ViSort
        run: | 
          $commands = @(
              'dotnet format ".\ViSort.sln" style --verify-no-changes',
              'dotnet format ".\ViSort.sln" whitespace --verify-no-changes',
              'dotnet format ".\ViSort.sln" analyzers --verify-no-changes'
          )

          foreach ($command in $commands) {
              $output = Invoke-Expression $command
              if ($output) {
                  $fail = $true
              }
          }
          
          if ($fail) {
            exit 1
          }
