name: XStyler Format Check

on:
  push:
    paths:
      - "**/*.xaml"
  pull_request:
    types:
      - ready_for_review
      - opened
      - reopened
  workflow_dispatch:

jobs:
  check:
    runs-on: windows-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0"

      - name: Install XStyler
        run: dotnet tool install XamlStyler.Console

      - name: Run Check
        shell: powershell
        run: |
          dotnet xstyler -r -d ViSort --passive
          if (! $?)
          {
            Write-Error "Please reformat"
            [Environment]::Exit(1)
          }
